### ISSUE TITLE
Why the fork?

### ISSUE THREAD

**Issue by NfNitLoop** [valtlai/nunjucks-deno#1]
I was just trying to use Nunjucks from https://esm.sh/nunjucks@3.2.3, and am running into some problems. I'm wondering if switching to your fork will fix things.  It would be nice if the README explained what this fork fixes/changes from the original.  :) 

Happy to see it on deno.land, though!  👍

**Comment by valtlai** [comment]
The whole purpose of this fork is to make Nunjucks work with Deno, because the auto conversion services, like ems.sh that you mentioned, don’t help.

The exact changes can be seen by looking at commit diffs and messages. I have tried to keep them atomic and have summarized the changes in the commit messages.
